[package]
name = "topsy-turvy"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["macros", "ws"] }
libsql = "0.9.9"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "process", "macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
