version: '3.8'
services:
  database:
    image: surrealdb/surrealdb:latest
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start 
      - --user
      - $SURREAL_USER
      - --pass
      - $SURREAL_PASS
    volumes:
      - ./init.surql:/docker-entrypoint-initdb.d/init.surql
    ports:
      - "8000:8000"

  app:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
